### ISSUE TITLE
ensure openvpn role is idempotent

### ISSUE THREAD

**Issue by adeck** [adeck/ansible-deployments#33]
I'm pretty sure it creates new CA certs and Diffie-Hellman keys every time.
Which would be really idiotic for actual long-term use.

So...
Fix that.

**Comment by adeck** [comment]
Done. Turns out there's a stupid bug in ansible. Filed a [bug report](https://github.com/ansible/ansible/issues/11829).
We shall see whether mdehaan just decides to close it. Apparently, half the time he closes bug reports before the bug's been fixed. Really shady operation they're running over there.

But whatever. It works well enough most of the time, and I suppose that's what matters.

**Comment by amenonsen** [comment]
You are welcome to help triage, test, and fix bugs in Ansible.

P.S. mpdehaan no longer works on Ansible.

**Comment by adeck** [comment]
@amenonsen Aw, man. Sorry- it's just been a long day. And yeah, I wouldn't be using it so much if it weren't really well written.

...I suppose I kinda owe you guys some code, now.
